### ISSUE TITLE
 As a student I can easily see my overall progress achieved for the different weeks on the dashboard.

### ISSUE THREAD

**Issue by HStewart23** [fac-15/FAC-TRACK#18]
Acceptance Criteria
- [ ] I can easily see all subjects
- [ ] I can see my progress shown as a fraction. 
- [ ] I can see me progress shown visually as pie chart thing. 

---

![dashboard](https://user-images.githubusercontent.com/39189687/51118170-a0048800-1807-11e9-962b-2568d3b01ab1.png)

**Comment by mr-bagglesworth** [comment]
Adding this to the general output student data to dashboard issue
