### ISSUE TITLE
Log task completion

### ISSUE THREAD

**Issue by HStewart23** [fac-15/FAC-TRACK#24]
**User Story:**
As a student I can log the completion level of a workshop/ challenge.

**Acceptance Criteria:**
- [x] I can mark a task as complete by clicking a checkbox
- [x] As a student I will be able to see a tick marker showing my selection made
- [x] As a student I can save my choice

**Comment by jcharnley** [comment]
- [ ] As a student I click on a check button to record that I have completed in all the steps within the workshop/challenge
- [ ] As a student I will be able to see a tick maker showing my selection made
- [ ] As a student I can save my choice
