### ISSUE TITLE
Dashboard Button in Footer

### ISSUE THREAD

**Issue by HStewart23** [fac-15/FAC-TRACK#26]
**User Story:**
As a student when I am not on the dashboard I can return to it via the footer.

- [x] As a student they can navigate to the dashboard when on another page via an icon on the footer
- [x] A a student they can easily see their index page via the footer
- [x] A a student they can click a back button via the footer

**Comment by jcharnley** [comment]
- [ ] As a student they can navigate to the dashboard when on another page via an icon on the footer
- [ ] A a student they can easily see their index page via the footer
- [ ] A a student they can click a back button via the footer
