### ISSUE TITLE
Display get request in browser

### ISSUE THREAD

**Issue by jcharnley** [fac-15/FAC-TRACK#44]
**User Story:** I can see a list of all weeks and all workshops for each week in the browser
> Take the get request data and display in the browser 
- [x] Test database query in pgcli / psql
- [x] Write successful database tests
- [x] Display the name/topic of each week on the **dashboard**
- [x] Display all workshops for each week when viewing an individual **week**
- [x] Display completed and confidence for a specific user

**Comment by mr-bagglesworth** [comment]
Material icons for the 4 icons we need can be found [here](https://www.materialpalette.com/icons)
Rather than downloading the whole font, I suggest copying the svgs for the following:
- tick
- forward
- back
- compass (don't think we need a 2nd link to dashboard though)
