### ISSUE TITLE
Get overall completion for a user

### ISSUE THREAD

**Issue by jcharnley** [fac-15/FAC-TRACK#69]
-  [x] get request from the database of completion of users week
-  [x] display this overall figure on the dashboard

**Comment by mr-bagglesworth** [comment]
I might suggest adding a research spike label (allocate time to research) for the doughnut chart for this one:
- [css only solution - with sass](https://codepen.io/seanstopnik/pen/Abyhj). This could work, but it would rely upon a lot of css classes written for each percentile, **or** css being written by javascript after the page has loaded - **i.e. a class to define fraction / percent has loaded in the html.**
- [css only solution using svg](https://stackoverflow.com/questions/20525820/css3-simple-donut-chart). As with the above, this would be non-responsive, and require css to be written after the page has loaded.
- alternative could be to use a library such as google charts or raphael, but a combination of one of the above methods with some frontend js will probably be more satisfying. [Google search on doughnut charts](https://www.google.com/search?q=doughnut+chart+css&oq=doughnut+chart+css&aqs)

**Comment by jcharnley** [comment]
If we done svgs's these can embed slugs or ahref links that will make them clickable and they scale well when at different viewpoints
